
export const FormActionTypes = {
    SIGN_OUT: 'SIGN_OUT',
    ON_CHANGE_EMAIL_FIELD : 'ON_CHANGE_EMAIL_FIELD',
    ON_CHANGE_PASSWORD_FIELD :'ON_CHANGE_PASSWORD_FIELD',
    ON_CHANGE_NAME_FIELD :'ON_CHANGE_NAME_FIELD',
    SUBMIT_PENDING : 'SUBMIT_PENDING',
    SUBMIT_SUCCESS : 'SUBMIT_SUCCESS',
    SUBMIT_FAILED : 'SUBMIT_FAILED'
  };

