
export const RegisterActionTypes = {
    ON_CHANGE_EMAIL_FIELD : 'ON_CHANGE_EMAIL_FIELD',
    ON_CHANGE_PASSWORD_FIELD :'ON_CHANGE_PASSWORD_FIELD',
    ON_CHANGE_NAME_FIELD :'ON_CHANGE_NAME_FIELD',  
    REGISTER_SUBMIT_PENDING : 'REGISTER_SUBMIT_PENDING',
    REGISTER_SUBMIT_SUCCESS : 'REGISTER_SUBMIT_SUCCESS',
    REGISTER_SUBMIT_FAILED : 'REGISTER_SUBMIT_FAILED'
  };

