
export const SignInActionTypes = {
    SIGN_OUT: 'SIGN_OUT',
    ON_CHANGE_EMAIL_FIELD : 'ON_CHANGE_EMAIL_FIELD',
    ON_CHANGE_PASSWORD_FIELD :'ON_CHANGE_PASSWORD_FIELD',
    SIGNIN_SUBMIT_PENDING : 'SIGNIN_SUBMIT_PENDING',
    SIGNIN_SUBMIT_SUCCESS : 'SIGNIN_SUBMIT_SUCCESS',
    SIGNIN_SUBMIT_FAILED : 'SIGNIN_SUBMIT_FAILED'
  };

