export const ImageLinkFormActionTypes = {
    ON_CHANGE_IMAGE_LINK: 'ON_CHANGE_IMAGE_LINK',
    IMAGE_LINK_FORM_SUBMIT_PENDING : 'IMAGE_LINK_FORM_SUBMIT_PENDING',
    IMAGE_LINK_FORM_SUBMIT_SUCCESS : 'IMAGE_LINK_FORM_SUBMIT_SUCCESS',
    IMAGE_LINK_FORM_SUBMIT_FAILED : 'IMAGE_LINK_FORM_SUBMIT_FAILED',
    INCREMENT_SUBMIT_PENDING : 'INCREMENT_SUBMIT_PENDING',
    INCREMENT_SUBMIT_SUCCESS : 'INCREMENT_SUBMIT_SUCCESS',
    INCREMENT_SUBMIT_FAILED : 'INCREMENT_SUBMIT_FAILED',
    CLEAR_LINK_FORM:'CLEAR_LINK_FORM',
    IMAGE_LINK_FORM_UPLOAD_PENDING:'IMAGE_LINK_FORM_UPLOAD_PENDING',
    IMAGE_LINK_FORM_UPLOAD_SUCCESS:'IMAGE_LINK_FORM_UPLOAD_SUCCESS',
    IMAGE_LINK_FORM_UPLOAD_FAILED:'IMAGE_LINK_FORM_UPLOAD_FAILED'
  };

